### ISSUE TITLE
Hide non required not working

### ISSUE THREAD

**Issue by themodfatherinc** [carlssonemil/vanguard#14]
In categories which I have diamond, it still shows the incomplete weapons and the category. I assume this is not how its intended to work. Not a big deal obviously but doesnt seem to be working correctly. Thanks for the tool though, its wonderful.

**Comment by themodfatherinc** [comment]
I just realized it works as long as you dont have hide completed also checked. Not sure if you could make the whole category/remaining weapon hide if diamond is complete. Wanted to be more specific about how to reproduce the issue.

**Comment by carlssonemil** [comment]
I think it's working as intended.

* **Hide completed**: Hide Gold weapons
* **Hide non required**: If you get Diamond in a category, it hides the remaining guns. 

If you want the entire category to be invisible when you get Diamond, you check both 😄 

Or is there some error which I can't reproduce on my end? Can you take a screenshot showing both the filter settings and the faulty category?

**Comment by themodfatherinc** [comment]
In categories where i have the base number of weapons complete to obtain diamond, but do not yet have all weapons complete, and i have both filter options checked, the incomplete weapon still appears. Specific example; Melee has gold knife and sawtooth. The Katana and Combat Shield still appear, and the count shows 0/1. In assault rifles, all gold except itra burst. itra burst still shows with count 0/1. If i tell it i have gold on the itra burst, and change nothing else, the whole category disappears. according to your explanation the category should also hide with the itra burst not complete? as long as i have enough weapons gold to have diamond? or is it in fact working as intended? 
in this specific example having 7 gold assault rifles once you check hide completed, the hide non required checkbox doesnt actually do anything. if you click it on and off nothing changes. same with the SMG category, 6 gold, not owen gun, SMG category still shows 0/1 and the owen gun no matter if you check hide non required or not

**Comment by themodfatherinc** [comment]
also i just noticed the count is wrong. I have 7 gold assault rilfes and it counts 6/6, smgs count at 5/5.

**Comment by carlssonemil** [comment]
Oh, yeah, you're right. Something is not working. I'll try and find the problem and see if I can fix it.

Also, regarding your last comment, the total count is how many weapons are required for Diamond, not how many weapons there are total. So there can be 8 total weapons but you only need to complete 7.

**Comment by whyyn0tt** [comment]
Any update on this? IMO "Hide Not Required" should simply hide the DLC (non-launch) weapons. It seemed to work on the MW2019 and BO:CW trackers in the past! Love your work, thanks!

**Comment by carlssonemil** [comment]
> Any update on this? IMO "Hide Not Required" should simply hide the DLC (non-launch) weapons. It seemed to work on the MW2019 and BO:CW trackers in the past! Love your work, thanks!

Sorry for not fixing this sooner, I briefly looked at it a few months back but completely forgot about fixing it. It should be fixed now.
