### ISSUE TITLE
Add camouflage images

### ISSUE THREAD

**Issue by carlssonemil** [carlssonemil/vanguard#2]
Add images for camouflages. Either by printing the screen in-game, or on a YouTube video, and extracting the individual camouflages from there with a image editing software - [Photopea](https://www.photopea.com/), Paint or Photoshop. 

Preferred size **125x125** and filetype **.png**. Place images in `src/assets/camouflages/` folder.

**Comment by carlssonemil** [comment]
Only images of the main camouflage categories are needed:
* Pack Tactics
* Surgical
* Predatory Ambition
* Reptilian
* Deadeye
* Berserker
* Wildcat
* Survivalist
* Mindgames
* Death Artist

Use [kebab case](https://www.theserverside.com/definition/Kebab-case) format, lowercase, when naming files. Ex.: `Pack Tactics` -> `pack-tactics.png`

**Comment by ItchyBeard** [comment]
Hey @carlssonemil - attempting to push a change to the repo, but it's giving me a 403 forbidden for both the main branch, and for one I created myself (so I can create a PR for it).

I've got two camo images, Pink Tactics and Predatory Ambition - along with updating some challenge text for the launchers on the other open issue (#1)

Once I unlock the camos' I'll be more than happy to add their images too, would you rather I upload as and when I get them, or just all 10 at the same time?

Cheers!
Itchy.

**Comment by carlssonemil** [comment]
Hey @ItchyBeard! 

That's odd. Have you followed the steps in the [contributing guidelines](https://github.com/carlssonemil/vanguard/blob/main/CONTRIBUTING.md)? Forking the repository and all that?

Feel free to add the images as you get them, all help is appreciated!

Cheers 😄

**Comment by ItchyBeard** [comment]
Ahh I cloned the main repo, made my changes and attempted to push (using the got client, Fork) - I didn't fork it, then clone the fork. 

I'll be back on my pc shortly and will follow those steps to the letter, apologies I should've read the guidelines first 😃

I appreciate all the work you've put in over the years with the camo trackers hah, the least I can do is contribute haha

Cheers again.

**Comment by carlssonemil** [comment]
No worries! Glad to have you onboard! 😁
