### ISSUE TITLE
 I started the cmd its brought me back to a website with camouflache I select but it does nothing in games

### ISSUE THREAD

**Issue by sofiane6700** [carlssonemil/vanguard#25]

**Comment by carlssonemil** [comment]
I'm still not sure what you mean, @sofiane6700? This tracker is completely separated from the game itself, nothing you change in the tracker will reflect in-game, and vice versa. I'm not sure what _cmd_ you're referring to either?

**Comment by carlssonemil** [comment]
Closing again due to inactivity. If you open another issue, please describe the issue in detail.
